import type { Metadata } from "next";

import RegistrationForm from "./components/registration-form";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RegistrationPage = () => {
  return (
    <div>
      <RegistrationForm />
    </div>
  );
};

RegistrationPage.displayName = "RegistrationPage";

export default RegistrationPage;
